// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

  The sidebars can be generated from the filesystem, or explicitly defined here.

  Create as many sidebars as you want.

  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated',   
    //  dirName: '.'}],

    OsSidebar: [
        {
            type: "category",
            label: "Operating System",
            link: {
                type: "doc",
                id: "index",
            },
            collapsed: true,
            items: [
                {
                    type: "category",
                    label: "Basics",
                    link: {
                        type: "doc",
                        id: "basic-intro/introduction",
                    },
                    collapsed: true,
                    items: [
                        {
                            type: "doc",
                            label: "Introduction",
                            id: "basic-intro/introduction"
                        },
                        {
                            type: "doc",
                            label: "Types of OS",
                            id: "basic-intro/types_of_os"
                        },
                        {
                            type: "doc",
                            label: "Kernel in OS",
                            id: "basic-intro/kernel_in_os"
                        },
                        {
                            type: "doc",
                            label: "System Call",
                            id: "basic-intro/system_call"
                        },
                        {
                            type: "doc",
                            label: "System Initialization",
                            id: "basic-intro/system_initialization"
                        },
                        {
                            type: "doc",
                            label: "User Mode and Kernel Mode",
                            id: "basic-intro/userlevel_kernel_level"
                        },
                        {
                            type: "doc",
                            label: "Fork System Call",
                            id: "basic-intro/fork"
                        },
                    ],
                },
                {
                    type: "category",
                    label: "Process Scheduling",
                    link: {
                        type: "doc",
                        id: "process_scheduling/process_intro",
                    },
                    collapsed: true,
                    items: [
                        {
                            type: "doc",
                            label: "Introduction",
                            id: "process_scheduling/process_intro"
                        },
                        {
                            type: "doc",
                            label: "Process Control Block",
                            id: "process_scheduling/process_control_block"
                        },
                        {
                            type: "doc",
                            label: "Process Table",
                            id: "process_scheduling/process_table"
                        },
                        {
                            type: "doc",
                            label: "Process Management Intro",
                            id: "process_scheduling/process_management_intro"
                        },
                        {
                            type: "doc",
                            label: "Process States",
                            id: "process_scheduling/process_states"
                        },
                        {
                            type: "doc",
                            label: "Process Schedulers",
                            id: "process_scheduling/process_schedulers"
                        },
                        {
                            type: "category",
                            label: "CPU Scheduling Algorithms",
                            link: {
                                type: "doc",
                                id: "process_scheduling/cpu_scheduling_algorithms",
                            },
                            collapsed: true,
                            items: [
                                {
                                    type: "doc",
                                    label: "FCFS Scheduling",
                                    id: "process_scheduling/fcfs"
                                },
                                {
                                    type: "doc",
                                    label: "SJF Scheduling",
                                    id: "process_scheduling/sjf"
                                },
                                {
                                    type: "doc",
                                    label: "SRTF Scheduling",
                                    id: "process_scheduling/srtf"
                                },
                                {
                                    type: "doc",
                                    label: "Round Robin Scheduling",
                                    id: "process_scheduling/round_robin"
                                },
                                {
                                    type: "doc",
                                    label: "Priority Scheduling",
                                    id: "process_scheduling/priority_scheduling"
                                },
                                {
                                    type: "doc",
                                    label: "HRRN Scheduling",
                                    id: "process_scheduling/hrrn"
                                },
                                {
                                    type: "doc",
                                    label: "Multilevel Queue Scheduling",
                                    id: "process_scheduling/multilevel_queue"
                                },
                                {
                                    type: "doc",
                                    label: "Multilevel Feedback Queue Scheduling",
                                    id: "process_scheduling/multilevel_feedback_queue"
                                },
                            ]
                        },
                        {
                            type: "doc",
                            label: "Preemptive vs Non-Preemptive",
                            id: "process_scheduling/preemptive_non_preemptive"
                        },
                        {
                            type: "doc",
                            label: "Dispatcher vs Scheduler",
                            id: "process_scheduling/dispatcher_vs_scheduler"
                        },
                        {
                            type: "doc",
                            label: "Starvation and Aging",
                            id: "process_scheduling/starvation_and_aging"
                        },
                    ],
                },
                {
                    type: "category",
                    label: "Process Synchronization",
                    link: {
                        type: "doc",
                        id: "process_synchronization/ipc",
                    },
                    collapsed: true,
                    items: [
                        {
                            type: "doc",
                            label: "Inter Process Communication (IPC)",
                            id: "process_synchronization/ipc"
                        },
                    ],
                },
                {
                    type: "category",
                    label: "Interview Questions",
                    link: {
                        type: "doc",
                        id: "Q&A/index",
                    },
                    collapsed: true,
                    items: [

                    ],
                },
            ],
        },
    ],
};

export default sidebars;
