// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

  The sidebars can be generated from the filesystem, or explicitly defined here.

  Create as many sidebars as you want.

  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated',   
    //  dirName: '.'}],

    OsSidebar: [
        {
            type: "category",
            label: "Operating System",
            link: {
                type: "doc",
                id: "index",
            },
            collapsed: true,
            items: [
                {
                    type: "category",
                    label: "Basics",
                    link: {
                        type: "doc",
                        id: "basic-intro/introduction",
                    },
                    collapsed: true,
                    items: [
                        {
                            type: "doc",
                            label: "Introduction",
                            id: "basic-intro/introduction"
                        },
                        {
                            type: "doc",
                            label: "Types of OS",
                            id: "basic-intro/types_of_os"
                        },
                        {
                            type: "doc",
                            label: "Kernel in OS",
                            id: "basic-intro/kernel_in_os"
                        },
                        {
                            type: "doc",
                            label: "System Call",
                            id: "basic-intro/system_call"
                        },
                        {
                            type: "doc",
                            label: "System Initialization",
                            id: "basic-intro/system_initialization"
                        },
                        {
                            type: "doc",
                            label: "User Mode and Kernel Mode",
                            id: "basic-intro/userlevel_kernel_level"
                        },
                        {
                            type: "doc",
                            label: "Fork System Call",
                            id: "basic-intro/fork"
                        },
                    ],
                },
                {
                    type: "category",
                    label: "Process Scheduling",
                    link: {
                        type: "doc",
                        id: "process_scheduling/process_intro",
                    },
                    collapsed: true,
                    items: [
                        {
                            type: "doc",
                            label: "Introduction",
                            id: "process_scheduling/process_intro"
                        }
                    ],
                },
                {
                    type: "category",
                    label: "Interview Questions",
                    link: {
                        type: "doc",
                        id: "Q&A/index",
                    },
                    collapsed: true,
                    items: [

                    ],
                },
            ],
        },
    ],
};

export default sidebars;
